import ThirdWebProviderComponent from "@/components/ThirdWebProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NFT MarketPlace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <ThirdWebProviderComponent>
          <Navbar />
          <div className="container mx-auto py-10" >
            {children}
          </div>
        </ThirdWebProviderComponent>
      </body>
    </html>
  );
}
