import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar";
import ThirdWebProviderComponent from "@/components/providers/ThirdWebProvider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NFT MarketPlace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <ThirdWebProviderComponent>
          <Navbar />
          <div className="container mx-auto py-10 max-w-7xl">{children}</div>
        </ThirdWebProviderComponent>
      </body>
    </html>
  );
}
